---
title: louisagr - blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blog construit avec Jekyll - Exercice Arinfo
baseurl: "/blog-jekyll"
url: https://louisagr.github.io
twitter_username: luizojero
github_username: louisagr
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- github-pages
