---
title: louisagr - blog
timezone: Europe/Paris
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: Louis
description: Construit avec Jekyll - Exercice Arinfo
baseurl: "/blog-jekyll"
url: https://louisagr.github.io
twitter_username: luizojero
github_username: louisagr
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- github-pages
