---
title: louisagr - blog
description: Construit avec Jekyll - Exercice Arinfo
baseurl: "/blog-jekyll" # the subpath of your site, e.g. /blog
url: "https://louisagr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luizojero
github_username: louisagr
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- github-pages
